project-ncl/project-manipulator

cli/pom.xml, cli/src/main/java/org/jboss/projectmanipulator/cli/Cli.java
=> Fix runability

README.md, cli/src/main/java/org/jboss/projectmanipulator/cli/Cli.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationException.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationSession.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, npm/pom.xml, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSessionFactory.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/DAException.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/ErrorMessage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/NVSchema.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/ReportMapper.java, pom.xml
=> [NCL-4196] Add support for NPM version autoincrement

npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, pom.xml
=> Fix compilation issues

npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java
=> Fix NPE when no user properties are provided

README.md
=> Document the system properties

README.md
=> Add more details to java properties description

README.md, cli/src/main/java/org/jboss/projectmanipulator/cli/Cli.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationSession.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSessionFactory.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmResult.java
=> [NCL-4268] Generate result.json file

core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java
=> [NCL-4320] Add option to disable alignment

README.md
=> [NCL-4320] Document option to disable npm alignment

README.md, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/NVSchema.java
=> [NCL-4319] Add option to specify DA repository group

npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java
=> [NCL-4370] Make evaluation of when DAcollector runs consistent

pom.xml
=> Jackson fix

npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java
Added tests along with some refactoring and minor fixes + added one more feature - replacing the suffix if one matching used pattern already exists.
=> [NCL-4394] Add automatic tests for supported features

cli/src/main/java/org/jboss/projectmanipulator/cli/Cli.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, core/src/main/java/org/jboss/projectmanipulator/core/Project.java, eclipse-codeStyle.xml, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSessionFactory.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/NVSchema.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/ReportMapper.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java, pom.xml
Style from: https://raw.githubusercontent.com/project-ncl/ide-config/master/eclipse/jboss-java-formatter.xml
Note: no new code was added in this commit. It's just application of the
codestyle
=> [NCL-1810] Use PNC ide-config style

core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, eclipse-codeStyle.xml, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java
=> [NCL-1810] 120 length for comments

eclipse-codeStyle.xml
=> [NCL-1810] Formatting for enum

npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageImpl.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java
=> [NCL-5619] Fix NPE when using versionOverride

.license-header.txt, cli/pom.xml, cli/src/main/assembly/bin.xml, cli/src/main/java/org/jboss/projectmanipulator/cli/Cli.java, core/pom.xml, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationException.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationSession.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, core/src/main/java/org/jboss/projectmanipulator/core/Project.java, eclipse-codeStyle.xml, npm/pom.xml, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSessionFactory.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageImpl.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmResult.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/DAException.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/ErrorMessage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/NVSchema.java, npm/src/main/java/org/jboss/projectmanipulator/npm/da/ReportMapper.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java, pom.xml
=> Mvn release

README.md, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmDependenciesManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmDependencyVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageImpl.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmResult.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmDependencyVersionManipulatorTest.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java, npm/src/test/resources/package.json, pom.xml
=> NCL-5595 - Add dependency versions manipulation; apply NCL-5601

npm/src/main/java/org/jboss/projectmanipulator/npm/NpmDependencyVersionManipulator.java
=> Fix logic that applies the manipulator

eclipse-codeStyle.xml, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java
=> [NCLSUP-94] Properly format array initializer

README.md, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationManager.java, core/src/main/java/org/jboss/projectmanipulator/core/ManipulationSession.java, core/src/main/java/org/jboss/projectmanipulator/core/Manipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmDependencyVersionManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackage.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageImpl.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageScopeManipulator.java, npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageScopeManipulatorTest.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java, pom.xml
=> [NCL-5919] Introduce scope manipulator and versioning strategies

npm/src/main/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/test/java/org/jboss/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java
=> [NCL-5919] Fix activation of version manipulator for SEMVER strategy

npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmDependencyVersionManipulator.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/ReportObjectMapper.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverReportMapper.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedReportMapper.java
=> [NCL-5946] Support version incrementing for semver versioning strategy

npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageVersionManipulator.java
=> [NCL-5946] Enhance the pre-release regexp

npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/ReportObjectMapper.java
=> Fix missing license headers

README.md, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageVersionManipulator.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverReportMapper.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedReportMapper.java
=> [NCL-6169] Update DA calls to the changed REST API

cli/src/main/java/org/jboss/pnc/projectmanipulator/cli/Cli.java
=> NCLSUP209 Prevent using log file in container

CHANGELOG.md, README.md, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/DAVersionsCollector.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SemverReportMapper.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedNVSchema.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/SuffixedReportMapper.java, npm/src/test/java/org/jboss/pnc/projectmanipulator/npm/NpmDependencyVersionManipulatorTest.java, npm/src/test/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageScopeManipulatorTest.java, npm/src/test/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageVersionManipulatorTest.java
=> [NCL-6556] Replace temporaryBuild flag by mode

cli/src/main/java/org/jboss/pnc/projectmanipulator/cli/Cli.java
This avoids the logged exception if it fails simply due to this file not existing.
=> Check if /proc/1/cgroup is readable before trying to open

npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/ReportMapper.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/da/ReportObjectMapper.java, pom.xml
=> Bump jackson and jackson-databind to 2.13.4.x

README.md, cli/pom.xml, cli/src/main/java/org/jboss/pnc/projectmanipulator/cli/Cli.java, npm/pom.xml, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/DAVersionsCollector.java, pom.xml
=> NCL-7444 Add OpenTelemetry Instrumentation

core/src/main/java/org/jboss/pnc/projectmanipulator/core/ManipulationException.java, core/src/main/java/org/jboss/pnc/projectmanipulator/core/ManipulationManager.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmDependencyVersionManipulator.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmManipulationSession.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageImpl.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageScopeManipulator.java, npm/src/main/java/org/jboss/pnc/projectmanipulator/npm/NpmPackageVersionManipulator.java
=> NCL-7444 Simplify exception handling

pom.xml
=> [v1.1.x] Bump gpg plugin version

pom.xml
=> Try to fix bump of gpg plugin

pom.xml
=> Bump Atlas version and JDK version

pom.xml
=> Migrate to Central Publisher
